---
title: "Getting started with PathwaySpace"
author: "Sysbiolab Team"
date: "`r Sys.Date()`"
bibliography: bibliography.bib
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bs4cards)
```

# Introductory vignettes

```{r, include=FALSE}
title <- c("Network Signal Projections", "Signal Decay Functions", "Signal Aggregation Rules")
image <- c("figs_intro/card1.png", "figs_intro/card2.png", "figs_intro/card3.png")
link <- c("projection-methods.html","modeling-signal-decay.html","signal-aggregation-rules.html")
ps_cards1 <- data.frame(title = title, image = image, link = link)
```

```{r, echo=FALSE}
ps_cards1 %>% 
  cards(
      title = title,
      image = image,
      link = link,
      layout = "label-below", 
      width = 3,
      border_radius = 5
  )
```

# Visualizing features in *PathwaySpace*

```{r, include=FALSE}
title <- c("Sparse Feature Sets", "Spatial Transcriptomics")
image <- c("figs_feature_sets/card1.png", "figs_spot_space/card1.png")
link <- c("sparse-feature-sets.html ","spatial-transcriptomics-doc1.html")
ps_cards2 <- data.frame(title = title, image = image, link = link)
```

```{r, echo=FALSE}
ps_cards2 %>% 
  cards(
      title = title,
      image = image,
      link = link,
      layout = "label-below", 
      width = 3,
      border_radius = 5
  )
```



