on:
  pull_request:
    branches: [main]

name: update-page-docs

jobs:
  update-page-docs:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes


    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install devtools
        run: |
          sudo  apt-get install -y \
          libssl-dev \
          libcurl4-openssl-dev \
          libharfbuzz-dev \
          libfribidi-dev
          Rscript -e 'install.packages("devtools")'

      - name: Prepare Git
        run: |-
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@github.com
          git checkout --orphan gh-pages

      - name: build-vignettes
        run: |
          Rscript -e 'devtools::load_all()'
          Rscript -e 'devtools::build_vignettes()'
          mv doc/PathwaySpace.html doc/index.html
          git add -f doc
          git commit -m 'Update github page' doc

      - name: Push docs to Github Pages
        run: |-
          git status
          git push origin `git subtree split --prefix doc gh-pages`:gh-pages --force
