on:
  pull_request:
    branches: [main]

name: update-page-docs

jobs:
  update-page-docs:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes


    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      
      - name: build-vignettes
        run: |
          Rscript -e 'devtools::load_all()'
          Rscript -e 'devtools::build_vignettes()'
